load_model: /home/derek/Documents/GraphMetaMat/logs/quick_run_v2/forward_checkpoints/model_epoch_snapshot_4.pt
load_model_IL: /home/derek/Documents/GraphMetaMat/logs/quick_run_v2/inverse_checkpoints/model_imitation.pt
load_model_RL: /home/derek/Documents/GraphMetaMat/logs/quick_run_v2/inverse_checkpoints/best_models/model_1024.pt

log_dir: /home/derek/Documents/GraphMetaMat/logs/quick_run_v2

plot_train_data: true
run_optuna_parallel: true
export_results: true
device: cuda

optimizer_decay: null
optimizer_RL:
    optimizer_name: Adam
    optimizer_args:
      lr: 0.001
      eps: 1.0e-3

optimizer:
    optimizer_name: AdamW
    optimizer_args:
      lr: 0.001
      eps: 1.0e-08
      weight_decay: 0.1

forward:
    train_config:
        num_epochs: 5000
        num_epochs_freeze_encoder: null
        num_epochs_per_valid: 200
        best_checkpoint_metric: neg_jaccard_all
        no_epoch_checkpoints: true
        clip_grad: 5.0
        plot_num_samples_max: 50
        use_snapshot:
            num_snapshots: 5
            t_mult: 1.0

inverse:
    train_config:
        num_imitation_epochs: 0
        num_iters: 0
        num_iters_per_train: 8
        num_iters_per_valid: 64
        save_interval: 1024
        norm_adv: true
        entropy_coeff: 0.0
        clip_grad: 0.01
        rl_algorithm: PPO
        clip_coeff: 0.15
        scale_reward: false
        norm_reward: false
        use_scheduler: null
        clip_reward:
            min: -1.0
            max: 1.0
    search:
        magnitude_coeff: 0.0
        shape_coeff: 0.0
        jaccard_coeff: 1.0
        uncertainty_coeff: -0.2
        constraint_n_nodes_min: 3
        constraint_n_nodes_max: 4
        constraint_rho_min: 0.02
        constraint_rho_max: 0.3
        constraint_rho_default: 0.15
        num_runs_valid: 2
        num_runs_test: 128
        n_iterations_rho_binary_search: 16
